// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYPGUm-L5zawGBBD2C_FkaTH0aQddr7SM',
    appId: '1:450095922894:web:1b35dae03733385471da9f',
    messagingSenderId: '450095922894',
    projectId: 'yeogi-itdae',
    authDomain: 'yeogi-itdae.firebaseapp.com',
    storageBucket: 'yeogi-itdae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_fHJSS4o-_YUq7aaw1wN5ppoiDtXIG7w',
    appId: '1:450095922894:android:d6cb609341b5584471da9f',
    messagingSenderId: '450095922894',
    projectId: 'yeogi-itdae',
    storageBucket: 'yeogi-itdae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGeaP1Q4bhEyA2MWXQ3oHqBHgfDwZ1wiY',
    appId: '1:450095922894:ios:b5bbdf93368b041671da9f',
    messagingSenderId: '450095922894',
    projectId: 'yeogi-itdae',
    storageBucket: 'yeogi-itdae.firebasestorage.app',
    iosBundleId: 'com.example.latte',
  );
}
